name: 60 Days Stale Check

on:
  schedule:
    - cron: '0 12 * * 6'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'codinasion/codinasion'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity.'
          days-before-stale: 60
          days-before-close: -1
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'ğŸ“ content,good first issue'
          exempt-issue-labels: 'ğŸ“ content,good first issue,track'