name: Pull Request Open Comment

on:
  pull_request_target:
    types:
      - "opened"
    branches:
      - "master"

permissions:
  issues: write
  pull-requests: write

jobs:
  comment_on_open:
    if: github.repository == 'codinasion/codinasion-programme' && github.event.pull_request.base.ref == github.event.repository.default_branch && github.event.pull_request.user.login != 'harshraj8843'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: `

              ðŸ‘‹ Hey @${{ github.event.pull_request.user.login }} 

              <pre>
                         _______________________________________________
                        |                                               |
                        |  ðŸ‘‹ Hey ${{ github.event.pull_request.user.login }}                         
                        |                                               |
                        |  ðŸ’– Thanks for opening this Pull Request ðŸ’–   |
                        |                                               |
               _/*\\_    |  This PR will be reviewed and merged shortly  |
              /__-__\\   |  _____________________________________________|
             (|~o.o~|)  /_/
               \\'-'/
              _/-v-\\_
             (   .   )
            / /  .  \\ \\
            \\ |  .  | /
             \\|=====|/
              |_.^._|       "The best error message is the one
              | |"| |        that never shows up."
              ( ) ( )       
              |_| |_|                        - Scott Hanselman
              </pre>
              `
            })
